### ISSUE TITLE
Tooltips in toolbar shouldn't hide icon nor open unexpected

### ISSUE THREAD

**Issue by se4598** [TGlas/tscript#1]
The buttons in the main toolbar have tool tips.

These tool tips should not:
1) hide (the look of) the button
2) open at unexpected locations (e.g. to the right of the last button ("configuration")

a possible solution for the toolbar (diff included CSS changes to be deleted and added):
```
.ide-toolbar {
  /* overflow: hidden; */
}

.tgui-control:hover .tgui-tooltip {
  /* opacity: 1; */
  display: block;
}

.tgui-tooltip {
  /* top: 3px; */
  /* opacity: 0; */
  top: 25px;
  display: none;
}
```
Or use the html title attribute and let the browser handle it. (works at least fine for text based ones)

**Comment by TGlas** [comment]
Thanks for the fix!
