### ISSUE TITLE
The error icon in the messages panel doesn't show on macOS

### ISSUE THREAD

**Issue by Jartreg** [TGlas/tscript#102]
The character used as the icon for error messages doesn't show on macOS. I tested it in Firefox, Safari and Chrome.

![](https://user-images.githubusercontent.com/28811733/136070359-438b8c7c-aab3-484f-8c9b-7b992400f686.png)

**Comment by Jartreg** [comment]
May be use the ℹ️-Emoji? Or keep the bullet and instead add a link/button called something like "View Documentation"/"More..."?

**Comment by TGlas** [comment]
The Emoji looks perfect. Is there a definite source where we can check browser/OS support? The button would also work, but with a text label it needs much more space. Maybe we can even make it a button containing only the icon, to make it stick out more clearly.

**Comment by Jartreg** [comment]
I don't know of any definite source for information on this. You can view how it looks using different fonts on [unicode-table.com](https://unicode-table.com/en/2139/) 🤷. However, I'm not sure which Emoji font is used by most Linux distros...
