### ISSUE TITLE
documentation: minor mistakes

### ISSUE THREAD

**Issue by sorachan** [TGlas/tscript#11]
I believe the EBNF syntax for anonymous functions is faulty: it is given as `lambda = "function" [ closure ] "(" param-list ") func-body" ;` both in the EBNF overview and the section on anonymous functions when I'm pretty sure it should be `lambda = "function" [ closure ] "(" param-list ")" func-body ;`.

Also, the misspelling of "ink" in the canvas graphics section ("inc") should be fixed. (I don't know if this misspelling appears in other places, I have so far only read the documentation sections I deemed relevant for my programming.)

**Comment by TGlas** [comment]
thanks, fixed!
