### ISSUE TITLE
Style error with curly brackets containing only a comment

### ISSUE THREAD

**Issue by ole0811sch** [TGlas/tscript#111]
### Description
When you have any kind of scope enclosed by curly brackets (if statements, just the curly brackets, for loops, ...) and don't have any statements but you do have a comment inside, it produces a Coding Style Violation; Invalid Line Indentation.

### To Reproduce

Any of these comments will produce this error

```
{
	#comment 1
}

for 0:1 do{
	#comment 2
}

if true then{
	#comment 3
}

while true do{
	#comment 4
}

```

Steps to reproduce the behavior and what was expected to happen instead:

1. Enable style errors
2. Use any of the examples above or any other such situation

What should happen instead: 
No error should occur as long as the comment has the right indentation.

**Comment by TGlas** [comment]
Thanks for the report. It turns out to be even worse - neither the control structure nor the comment are needed to produce the error. The following entirely trivial example suffices:

    {
    }

**Comment by TGlas** [comment]
Should be fixed.
