### ISSUE TITLE
Internal Error with canvas.mouseout event and breakpoint

### ISSUE THREAD

**Issue by ole0811sch** [TGlas/tscript#112]
### Description
If you execute the code with the breakpoint and move the mouse out of the canvas, you get a `internal interpreter error; t.type is undefined` error. Also the IDE says the program's still running, even though it isn't, which doesn't seem intentional.

### To Reproduce

Example code:
```
function mouse_out(event)
{
	;	#the breakpoint goes here
}

setEventHandler("canvas.mouseout", mouse_out);
enterEventMode();
```

Steps to reproduce the behavior and what was expected to happen instead:

1. Enter the code
2. Add a breakpoint at the line marked with the comment
3. Run the program and trigger the mouseout event by moving the mouse from inside the canvas to the outside

Any statement works in place of the semicolon as well.

**Comment by TGlas** [comment]
Thanks for the report. The bug is now fixed.
