### ISSUE TITLE
Internal Error with mouseout event and print(event)

### ISSUE THREAD

**Issue by ole0811sch** [TGlas/tscript#113]
### Description
Likely related to the other bug with the mouseout event. When you execute the code and move the mouse out of the canvas, (without breakpoints this time) an `internal interpreter error; i.type is undefined` error occurs. (note that it says i.type this time instead of t.type).

### To Reproduce

Example code:
```
function mouse_out(event)
{
	print(event);
}

setEventHandler("canvas.mouseout", mouse_out);
enterEventMode();
```

Steps to reproduce the behavior and what was expected to happen instead:

1. Enter the code
2. Run the program and trigger the mouseout event by moving the mouse from inside the canvas to the outside

**Comment by TGlas** [comment]
Thanks for the report. The bug is now fixed.
