### ISSUE TITLE
Internal interpreter error in canvas functions for array arguments containing user-defined objects

### ISSUE THREAD

**Issue by Mindena** [TGlas/tscript#120]
### Description
Calling any of the functions `curve`, `fillArea`, `frameArea` or `transform` in the `canvas` namespace with arrays containing non-builtin objects results in the message `internal interpreter error; Cannot read properties of undefined (reading 'length')`.

### To Reproduce
```
class A {}
var a = A();

# Raise internal interpreter error:
# canvas.curve([a], false);
# canvas.fillArea([a]);
# canvas.frameArea([a]);
# canvas.transform([a, a], [a, a]);

# Raise runtime type error as expected:
# String.fromUnicode([a]);
# audio.MonoSound([a], 8000);
# audio.StereoSound([a], [a], 8000); 
```

**Comment by TGlas** [comment]
Thanks for the bug report. I will add a fix and corresponding unit tests soon.
