### ISSUE TITLE
Function in For Loop: Variable Access

### ISSUE THREAD

**Issue by pfz4** [TGlas/tscript#125]
Hello,
I'm currently reimplementing the interpreter in Rust and noticed an error with accessing a variable inside a function inside a for loop. I think it is best described by the tests below. A Variable that is created by a for-loop can't be used inside a function inside a for-loop. A Variable created by an assignment can be used inside a function inside a function. 

### Code
```tscript
var a = "a";
for var i in 0:2 do {
	function foo(){
		print(a);
	}
	foo();
}
```
### Result
```
a
a
```

### Code
```tscript
for var i in 0:2 do {
        var a = "a";
	function foo(){
		print(a);
	}
	foo();
}
```
### Result
```
a
a
```

## Test No.3
```tscript
for var a in ["a","a"] do {
	function foo(){
		print(a);
	}
	foo();
}
```
### Result
```
runtime error in line 3: variable 'a' was used before it was initialized
```

## Test No.4
```tscript
for var a in ["a","a"] do {
	var b = a;
	function foo(){
		print(b);
	}
	foo();
}
```
### Result
```
a
a
```

**Comment by TheHllm** [comment]
When you are done with the interpreter in rust, could you write an llvm frontend too?

**Comment by TGlas** [comment]
Thanks for the report. Feel free to create a PR, otherwise I'll also look into this.

For the rust implementation: there is already a C++ implementation, created in the scope of a BA thesis. If you are interested in joining forces or discussing the design the let me know.

**Comment by pfz4** [comment]
> When you are done with the interpreter in rust, could you write an llvm frontend too?
I will take a look at LLVM when the interpreter is running :)

> For the rust implementation: there is already a C++ implementation, created in the scope of a BA thesis. If you are interested in joining forces or discussing the design the let me know.
I will contact you to discuss the planned design of the interpreter once I have brought my ideas for the design to paper.

Furthermore, I've taken some time to look at the bug:

The working examples above only work because the variables declared by the "var" keyword have the "global" scope. If the whole thing is wrapped in another function, the child-function can't access the variables or parameters of the parent function because they are "local".

This behavior is caused by the parse_expression and resolve_name function.
The resolve_name function checks that a "local" scoped variable lives in the same function and throws the "ne-7" error otherwise. I think that this function should check if the variable is owned by a parent or grandparent of the current function before throwing that error.
It doesn't throw the error if the for loop is in the global body because the variable context is "global scope".

The resolve_name function only tries to get the value of variables with "local" scope from the frame on top of the stack. It would have to search the parents too, or the function frame would have to get created with the parameters and the parent variables as the local variables. The variable created by the for-loop has "local" scope, so the parse_expression function tries to access it in the current frame but can't find it because the current frame changed when the function was called. Because the resolve_name function can't find the value of the variable in the current frame, it thinks that it never got initialized.

**Comment by TGlas** [comment]
Thanks for looking into this a bit deeper. The error message is indeed misleading.
Here is another example:

    var f;
    {
        var a = 42;
        f = function() { print(a); };
    }
    f();

It works, which it should not, because by the time `f` is called, `a` already ran out of scope.

It seems that the current distinction between global and local is not too useful. Currently variables within a scope but outside of a class or function are considered global. That causes problems. For this purpose, the relevant distinction should be the lifetime of the variable. "Global" access should be granted only to variables with unlimited lifetime, i.e., those living really in the global scope (not in sub-scopes), namespaces, and static variables in classes.
