### ISSUE TITLE
Error messages display wrong files with some parsing errors

### ISSUE THREAD

**Issue by David0x03** [TGlas/tscript#131]
### Description
With some parsing errors, when they happen to occur in files, which get included in the project, the displayed error messages show them to occur in the open file instead of the included file.

### To Reproduce
Minimal example:
![error_desc](https://github.com/TGlas/tscript/assets/28739366/221a696d-9318-48dc-ba8e-9947996bf6c2)

What should happen instead:
The error message should read `"error in file 'MakeError' in line 1; error in expression; 'a' is not defined"`

**Comment by TGlas** [comment]
Thanks for the report. This should be fixed by #[43de90a](https://github.com/TGlas/tscript/commit/43de90a5fce3e08b5d51d815e762448d609a86bc).

I'll close this for now. Please feel free to re-open at need.
