### ISSUE TITLE
Sample code freezes documentation

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#14]
Documentation pages with a code sample like [The Type Type](https://tglas.github.io/tscript/distribution/index.html?doc#/language/types/type) freeze the documentation. On further inspection the problem lies [in the function `checkCode` in doc.js at line 370](https://github.com/TGlas/tscript/blob/4f2b0e7d16476f4cd709b2336f598f436db611d1/source/doc.js#L370). It gets stuck in the loop. Changing `interpreter.step_into();` to `interpreter.step();` fixed it for me. I also suggest to change `step` to `exec_step` or similar to avoid confusion.

[Fix](https://github.com/manuel-fischer/tscript/commit/14afaa3735a32996566e2fd9e82d345906a8620b)

**Comment by TGlas** [comment]
Thanks for the analysis - should be fixed now. This was a follow-up of a small restructuring necessary to fix issue #13.
