### ISSUE TITLE
Mutability of closures

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#17]
There should be a mention about the closure being constant for the lifetime of the function,
as it is mentioned in "Informatik 1 - Einheit 9 - Anonyme Functionen" on slide 18

> * `p` und `q` werden bei der Erstellung der Funktion festgelegt. Sie bleiben während der gesamten Lebensdauer der anonymen Funktion gleich

Closure variables are copied to the local frame of the function, when executed (see [source/tscript.js:2859](https://github.com/TGlas/tscript/blob/b5b7f98f99810b438ba8cd2ff295ad37e69b997b/source/tscript.js#L2859): the closure array is concated with the parameter array, resulting in a new independent array).
So any changes of the closure variables only affect the local frame.

In my personal opinion, changes to the closure variables should affect the the function object itself, as it happens in C++.
An example where this is useful, are functions that need mutable state like a simple counter:

	var counter = function[i=0]()
	{
		i += 1;
		return i;
	};
	
	print(counter()); # 1
	print(counter()); # 1 should be 2

**Comment by TGlas** [comment]
fixed.
