### ISSUE TITLE
Bug in Date class example: Date.fromDMY

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#19]
The `Date` class example in the documentation for classes has a minor bug in the `fromDMY` function when handling leap years. All dates constructed with `Date.fromDMY` are off by one day, when the year is a leap year.

`Date.fromDMY(15, 1, 2020).prettyString()` results in `16.01.2020`.

There is a simple fix, `leapyears` counts all the leapyears since 1968 including the current one, but it is used as if it only counts the leapyears in the previous years

`var leapyears = (year - 1968) // 4; # the number of leapyears between ]1968, year]`

should be

`var leapyears = (year - 1 - 1968) // 4; # the number of leapyears beween ]1968, year[`

**Comment by TGlas** [comment]
Thanks, good find! Fixed.
