### ISSUE TITLE
Programm Demos

### ISSUE THREAD

**Issue by ThorgerJ** [TGlas/tscript#20]
Two of the three demo programs are not working under firefox windows 10. Snowflake is the one working.

**Comment by TGlas** [comment]
Interesting - it works fine in FF on Ubuntu. Two questions:
1. Do you see anything in the error console?
2. Do the [corresponding example programs](https://github.com/TGlas/tscript/tree/master/examples) work?

**Comment by ThorgerJ** [comment]
2. The examples work when copied into the TScript IDE and executed within it. When refreshing the page of the regular samples (the ones linked in the readme) sometimes the first frame is visible for a few ms. Adblock is not active and noscript is not installed.
1. The only Output for all three samples is "MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead." - its a warning not an error

**Comment by TGlas** [comment]
It "should" be fixed now. Could you try once more?

**Comment by ThorgerJ** [comment]
I had to use an incognito tab (probably still caged) - it seems to work now 👍
