### ISSUE TITLE
Integer.constructor only supports signless numeric strings

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#22]
`Real.constructor` and `Integer.constructor` can be used for parsing numbers from a string.
`Real.constructor` supports numbers with a sign (`+` or `-`), but `Integer.constructor` only supports numbers that have no sign.

    print(Real("-123"));
    print(Integer("-123"));
    print(Real("+42"));
    print(Integer("+42"));

**Comment by TGlas** [comment]
Thanks, fixed!
