### ISSUE TITLE
There is no obvious way to close the open and save dialogs.

### ISSUE THREAD

**Issue by se4598** [TGlas/tscript#4]
All dialogs should have a obvious way to close/cancel them (if applicable).

Currently apparently only the configuration dialog states that you can close the dialog by pressing ESC, although the open and save dialogs can also be closed by pressing ESC.

Can be fixed by offering cancel buttons (or alternatively a  "X" button/icon or writing the same text as in the configuration dialog).

I prefer the first proposed solution or combination of the first two. But it should be consistent.

**Comment by TGlas** [comment]
Added cancel and close buttons to all dialogs.
