### ISSUE TITLE
Dialogs could be improved

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#41]
![grafik](https://user-images.githubusercontent.com/58823087/100776319-af454c80-3404-11eb-82ae-1c3c03e9cd56.png)

On the left there is the current load file dialog, on the right there is my improved version that I drew. I will describe the changes and the issues the current gui has.

- The problem with the current buttons
  - inconsistency: some buttons show the hand cursor([Delete file] etc...) others show the normal arrow ([Okay] and [Cancel])
  - either the buttons could be changed to be 3D or to go with the modern look, the look could change like the following
    - this would give the user feedback that there is a button that is clickable
    - 1: normal state, 2: mouse over state, 3: mouse button down state
![grafik](https://user-images.githubusercontent.com/58823087/100778187-fcc2b900-3406-11eb-8790-d5685ca529b5.png)
- X-button to close the dialog: its sometimes hard to directly see the cancel button (file dialogs) or the close button (configuration), it might be useful if there was an additional X-button in the titlebar of the dialog
- Arrangement of buttons in the file dialogs
  - I suggest to only keep [Okay] and [Close] at the bottom of the dialog and move the other three buttons above the file list, this would distinguish the two types of buttons:
    - [Okay], [Close]: buttons that close the dialog
    - [Delete], [Import], [Export]: that operate on the files in the list and don't close the dialog
  - Toolbar:  [Delete], [Import], [Export] can also be icon buttons.
    - Status bar: shows information about all files or the currently selected file (number of lines, date, etc.) specifically
- Double click on list element in file dialogs should confirm the selected file
- Also add text box to the load file dialog, it might be useful to search for a file, when there are many files
  - when there is text in the text box, elements in the list, that contain the text, could be filtered or highlighted
  - the best match could be selected

- I also painted a Export all button, that might be helpful when creating backups of the files.
  - it might also export all the json data stored by the TScript function `save`

# Edit
- The [Import] button closes the dialog but does not open the imported file when it was imported.
  - I suggesst that the dialog keeps open, so other files can also be imported, and the newly imported file is selected

I am working on this in my branch [gui-improvements](https://github.com/manuel-fischer/tscript/tree/gui-improvements)

**Comment by TGlas** [comment]
I totally agree. The dialogs started out with minimal functionality, rather quick and dirty. They never got much attention. Then more functionality was added over time, without any guidelines. Doing a systematic rehersal is a good idea, since usability is important. I am looking forward to the improved version!

**Comment by Jartreg** [comment]
The import button probably just closes the dialog to avoid [a specific case](https://github.com/TGlas/tscript/pull/33#discussion_r527645625) which would lead to an error after import.

**Comment by Jartreg** [comment]
Since you are already working on this, would you mind creating a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) for this? This way it might be easier to follow the development.

**Comment by manuel-fischer** [comment]
Yes: https://github.com/TGlas/tscript/pull/45
