### ISSUE TITLE
Self-XSS

### ISSUE THREAD

**Issue by jonasmoos** [TGlas/tscript#43]
Ich habe eine XSS Schwachstelle in der TScript-IDE gefunden.

Betroffen sind die Funktion cmd_load(...) und cmd_save_as(...). Hier lässt sich der Dateiname ausnutzen mit beispielsweise dem Html-Tag `<img src=x onerrror=alert(document.domain)>`, um JavaScript auszuführen. Das Problem liegt festlegung des Editor-Namen auf den Dateinamen. Dieser wird mit [element.innerHTML](https://developer.mozilla.org/de/docs/Web/API/Element/innerHTML) in die Seite eingebettet und kann für Cross-Site-Scripting ausgenutzt werden.

Auch wenn das Potenzial der Schwachstelle gering ist, da eine Nutzerinteraktion nötig ist, lässt es sich auf einfach Art und Weise vermeiden, in dem die Festlegung des Namen mit [element.innerText](https://developer.mozilla.org/de/docs/Web/API/Node/innerText) erfolgt.

Schritte zum Reproduzieren:
1. Eine Datei mit beliebigem Inhalt erstellen.
2. Diese Speichern-Unter mit dem Namen `<img src=x onerrror=alert(document.domain)>`
Auch beim öffnen der Datei wird das Script ausgeführt.

Mit freundlichen Grüßen
Jonas Moos

**Comment by Jartreg** [comment]
@TGlas Since you fixed this in 6cead9e1ae0ac046b872817b288b87b3fa946508 this issue can be closed

**Comment by TGlas** [comment]
Sure :) Sorry, I forgot.
