### ISSUE TITLE
Turtle Window Size influence

### ISSUE THREAD

**Issue by ThorgerJ** [TGlas/tscript#6]
When using the turtle to draw lines or objects they are scaled proportionally to the window containing the drawing. This means a perfect square could rather look like a rectangle (depending on the window proportions) which might be confusing to new users.

**Comment by TGlas** [comment]
Good point, I was lazy when implementing this. Fix: The drawing area is now always square and remains centered inside the turtle panel.

**Comment by TGlas** [comment]
I think that would be equally surprising. For the turtle I aim at the simplest possible drawing model, which means that there should be a fixed coordinate range (here -100 to +100). This design is in contrast to the canvas, where pixel-perfect drawing is doable. It comes at the price that one needs to query the size and scale the drawing accordingly. For the turtle I'd like to guarantee the same result no matter how the panel is shaped.
