### ISSUE TITLE
Canvas won't resize in an export

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#74]
When exporting as a canvas application, it won't resize the canvas when the browser window is resized.

This might be related to #62 where the canvas is fully invisible. Some browsers might use a viewport size of 0×0px when the webpage is currently hidden (other browser tab activated).

**Comment by Jartreg** [comment]
This is not a bug but rather a feature request (enhancement), since canvas resizing is not implemented at all for exports. I also think that this could help with #62, however the issue described there also occurs when opening the page in the foreground.

**Comment by TGlas** [comment]
Well, the canvas has a resize event. So I find it reasonable to expect the event to fire when the window is resized. Therefore I tend to consider this a bug.

**Comment by TGlas** [comment]
I created the branch standalone-canvas-fixes, could you check if it helps on your side? I would be particularly interested in other browser/OS combinations.

**Comment by TGlas** [comment]
I merged the branch, and it seems to work now - but the tested browser/OS combinations were not exhaustive. I'll close this for now. If you experience further problems then please reopen with additional details.
