### ISSUE TITLE
For loop varible redefinition

### ISSUE THREAD

**Issue by TheHllm** [TGlas/tscript#78]
### Description  
I TScript class names may not be reused as a variable name.
This however dose not apply to for loops.

### To Reproduce
```
var A = 10;
for var A in 1:2 do {
	print(A);
}
```

**Comment by Jartreg** [comment]
I think this is intended behaviour, since the for loop is a new scope. In nested scopes, names can be reused without affecting the outer scope (see [variable shadowing](https://en.wikipedia.org/wiki/Variable_shadowing)).

Code example:

```py
class A {

}

# This would yield an error,
# since A is already declared in _this scope_:
var A = 10;

{
	# This is a new scope,
	# A can be safely shadowed:
	var A = 10;
}
```

**Comment by TheHllm** [comment]
Hmm i see that makes a lot of sense. 
And having the declaration be "part" of the body of the for loop is also not unusual (see js).

**Comment by TGlas** [comment]
Just to confirm: Yes, this is intended. I agree that with a type name the situation is somewhat more surprising than with a variable declared in an outer scope. In TScript, even the following works:

    for var Integer in 0:10 do print(Integer);

This is just a scoping thing. Integer is a name defined at global scope, but the for-loop opens a new sub-scope. The behavior is in no way specific to for loops, as shown by the following example:

    {
        var Integer;
        for Integer in 0:10 do print(Integer);
    }

For variables this shadowing behavior is common. One could debate whether it should be possible to shadow the name of a type or not. If you see a need to discuss this further then please re-open the issue.
