### ISSUE TITLE
Auto Fill for the Code windows

### ISSUE THREAD

**Issue by ThorgerJ** [TGlas/tscript#8]
The windows usually automatically change the size when elements are removed. However when removing the canvas and other elements on the right side the code and debug window are not rescaled automatically

![image](https://user-images.githubusercontent.com/48259372/67873285-8254a500-fb33-11e9-9362-837536afcaac.png)

**Comment by TGlas** [comment]
This is because the IDE uses a fixed two-column layout. Well, one could of course make it single-column if one of the columns is empty.

**Comment by TGlas** [comment]
If one column is empty then the other column now takes up the full horizontal space.
